//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onpe.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Estado { get; set; }
        public string Codigo { get; set; }
        public string Password { get; set; }
        public int RolId { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
